# Generated by Django 5.1.4 on 2025-11-15 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=125)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Activo', max_length=45)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('privado', models.IntegerField(default=0)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nom_tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('dias1', models.IntegerField(blank=True, null=True)),
                ('dias2', models.IntegerField(blank=True, null=True)),
                ('dias3', models.IntegerField(blank=True, null=True)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(blank=True, choices=[('Enel', 'Enel'), ('Municipal', 'Municipal'), ('Notarial', 'Notarial'), ('Sedapal', 'Sedapal'), ('Sunarp', 'Sunarp'), ('Privado', 'Privado')], max_length=45, null=True)),
                ('numero', models.CharField(blank=True, max_length=11, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('presentacion', models.DateField(blank=True, null=True)),
                ('reingreso', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intranet.ot')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('allday', models.BooleanField(default=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.ot')),
            ],
        ),
        migrations.AddField(
            model_name='ot',
            name='id_tipot',
            field=models.ForeignKey(blank=True, db_column='id_tipot', null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.tipot'),
        ),
    ]
