# Generated by Django 5.1.4 on 2025-11-15 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intranet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('todo', 'Por Hacer'), ('in_progress', 'En Progreso'), ('review', 'En Revisión'), ('done', 'Hecho')], default='todo', max_length=20, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('high', 'Muy Urgente'), ('medium', 'Urgente'), ('low', 'Estable')], default='low', max_length=10, null=True)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.ot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2250, null=True)),
                ('comentario', models.CharField(blank=True, max_length=10000, null=True)),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intranet.ot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.tarea')),
            ],
        ),
    ]
