# Generated by Django 5.1.4 on 2025-11-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('ingreso', models.DateTimeField(blank=True, null=True)),
                ('puesto', models.CharField(blank=True, max_length=45, null=True)),
                ('tip_cuenta', models.CharField(blank=True, choices=[('BCP', 'BCP'), ('CCI Banco de la Nación', 'CCI Banco de la Nación'), ('CCI BBVA', 'CCI BBVA'), ('CCI Interbank', 'CCI Interbank'), ('CCI Scotiabank', 'CCI Scotiabank'), ('Otro', 'Otro')], max_length=45, null=True)),
                ('num_cuenta', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('telf_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('nom_emergencia', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.area')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
